colors:
  primary:
    background: "#1a1b26"
    foreground: "#c0caf5"

  normal:
    black:   "#15161E"
    red:     "#f7768e"
    green:   "#9ece6a"
    yellow:  "#ff9e64"
    blue:    "#7aa2f7"
    magenta: "#bb9af7"
    cyan:    "#7dcfff"
    white:   "#a9b1d6"

  bright:
    black:   "#414868"
    red:     "#f7768e"
    green:   "#9ece6a"
    yellow:  "#e0af68"
    blue:    "#2ac3de"
    magenta: "#bb9af7"
    cyan:    "#7dcfff"
    white:   "#c0caf5"

window:
  padding:
    x: 2
    y: 2

font:
  normal:
    family: HackNerdFont
    style: Regular
  
  size: 12
